# Define locations for which builds should be created.
# For each build we specify a subsampling scheme via an explicit key.
builds:

  colorado:
    subsampling_scheme: state
    country: USA
    division: Colorado

  coloradous:
    subsampling_scheme: state-us
    country: USA
    division: Colorado

subsampling:

  state:
    focal:
      group_by: "month"
      max_sequences: 2900
      query: --query "country == '{country}' and division == '{division}'"

  state-us:
    focal:
      group_by: "month"
      max_sequences: 2700
      query: --query "country == '{country}' and division == '{division}'"

    # Samples that are genetically related to the focal samples
    national-context:
      group_by: "usa_region month"
      seq_per_group: 5
      query: --query "country == '{country}' and division != '{division}'"
    


   
